linux-dreambox.inc: Remove PKG:{PN} which rename to existing package
ERROR: linux-dreambox-3.2-r14.20.90 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists